# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('trip_location', models.CharField(max_length=200)),
                ('trip_start_date', models.CharField(max_length=50)),
                ('trip_end_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
