# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goNow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_from_you',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_budget',
            field=models.IntegerField(default=0),
        ),
    ]
